version: "3"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev

  frontend-server:
    build: ./client
    container_name: client
    ports:
      - 3000:3000

  backend-server:
    build: ./server
    container_name: server
    ports:
      - 4000:4000
