version: "3.9"
services:
  db:
    container_name: mysql
    build: ./db
    command: 
      --default-authentication-plugin=mysql_native_password
      #--init-file /init.sql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: dev
      MYSQL_USER: dev

  frontend-server:
    build: ./client
    container_name: client
    ports:
      - 3000:3000

  backend-server:
    build: ./server
    container_name: server
    ports:
      - 4000:4000
volumes:
  dbdata: