version: "3.9"
services:
  db:
    container_name: mysql
    build: ./db
    command: 
      --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}

  frontend-server:
    build: ./client
    container_name: client
    ports:
      - 3000:3000
    environment:
      RUN_COMMAND: ${RUN_COMMAND} 
      AUTH0_DOMAIN: ${AUTH0_DOMAIN} 
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID} 
    volumes:
      #only on dev
      - /client/src:/src
  backend-server:
    build: ./server
    container_name: server
    ports:
      - 4000:4000
    environment:
      DB_PASS: ${DB_PASS}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
    volumes:
      #only on dev
      -  /server/src:/src
volumes:
  dbdata: